import Home from './Home'
import About from './About'
import SignIn from './Auth/SignIn'
import SignUp from './Auth/SignUp'
import Forgot from './Auth/Forgot'
import Reset from './Auth/Reset'
import Profile from './User/Profile'
import Password from './User/Password'
import Avatar from './User/Avatar' 
import Create from './User/Create'
import List from './User/List'
import Update from './user/Update'
import Article from './Article'
import Blog from './Blog'
import Category from './Admin/Category'
import CategoryList from './Admin/CategoryList'
import CreateCategory from './Admin/CreateCategory'
import Dashboard from './Admin/Dashboard'
import Login from './Auth/Login'
import UserLayout from './User/UserLayout'
import AdminLayout from './Admin/AdminLayout'
import AuthLayout from './Auth/AuthLayout'
import Users from './Admin/Users'
import Articles from './User/Articles'

export { Home , About, SignIn, SignUp,Forgot,Reset,Password,Profile,Avatar,Category,Create,CategoryList,CreateCategory,Login, Dashboard,Blog,Article,Update,List,UserLayout,AdminLayout,AuthLayout,Users,Articles
}